# Generated by Django 2.0.1 on 2018-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='latitude',
            field=models.IntegerField(default=39.90923, verbose_name='景点纬度'),
        ),
        migrations.AddField(
            model_name='story',
            name='longitude',
            field=models.IntegerField(default=116.397428, verbose_name='景点经度'),
        ),
    ]
