# Generated by Django 2.0.1 on 2018-07-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_platform', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
